import { describe, it, expect } from "vitest";
import { part1, part2 } from "./index";

const exampleInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;

describe("Day 07 Part 1", () => {
  it("should return the correct answer for the example", () => {
    expect(part1(exampleInput)).toBe(21);
  });
});

describe("Day 07 Part 2", () => {
  it("should return the correct answer for the example", () => {
    expect(part2(exampleInput)).toBe(40);
  });
});

